name: Test and Create Issue on Failure

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Choose a Python version that works for you

    - name: Set execute permissions
      run: |
        chmod +x ./check-doctype.js
        chmod +x ./check-doctype.sh

    - name: Check DOCTYPE declaration
      id: check-doctype
      run: |
        ./check-doctype.js || ./check-doctype.sh
      continue-on-error: true

    - name: Create Issue on Failure
      if: steps.check-doctype.outcome == 'failure'
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "Bug: Missing DOCTYPE Declaration in index.html"
        labels: bug
        assignees: your_username
        body: |
          The index.html file is missing the required DOCTYPE declaration on the first line. Please fix this issue.
